server:
  port: 18082
spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/altaf
    username: altaf
    password: altaf

keycloak:
  realm: altaf
  auth-server-url: http://localhost:8080
  resource: spring-keycloak
  public-client: true
  bearer-only: true
